"""REST adapter for the transport-neutral City engine and room service."""

from __future__ import annotations

import hmac
import os
from functools import lru_cache
from typing import Any, Literal

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request, Response, status
from pydantic import BaseModel, Field

from city_engine.commands import Command
from city_engine.constants import MAX_PLAYERS, MIN_PLAYERS
from city_engine.content import load_catalog
from city_rooms.errors import RoomValidationError
from city_rooms.models import ClientInfo, RoomState
from city_rooms.repository import InMemoryRoomRepository
from city_rooms.service import CityRoomService
from city_rooms.upstash import UpstashRoomRepository
from city_rooms.views import room_journal, room_view

router = APIRouter(prefix="/api/city", tags=["city"])


class CreateRoomRequest(BaseModel):
    name: str = Field(min_length=1, max_length=48)
    # Empty for an open lobby; a private room still needs 4+ characters (checked by the service).
    password: str = Field(default="", max_length=128)
    open: bool = False
    # Secrets generated by the browser; the server keeps only their hashes.
    owner_token: str = Field(default="", max_length=128)
    capacity: int = Field(default=4, ge=MIN_PLAYERS, le=MAX_PLAYERS)
    max_rounds: int = Field(default=15, ge=5, le=30)
    role_price: int = Field(default=3, ge=2, le=10)


class JoinRoomRequest(BaseModel):
    password: str = Field(default="", max_length=128)
    seat_index: int = Field(ge=0, le=MAX_PLAYERS - 1)
    player_name: str = Field(min_length=1, max_length=32)
    release_seat_index: int | None = Field(default=None, ge=0, le=MAX_PLAYERS - 1)
    seat_token: str = Field(default="", max_length=128)


class TutorialRequest(BaseModel):
    player_name: str = Field(min_length=1, max_length=32)
    lang: Literal["ru", "en", "cs"] = "ru"


class SeatRequest(BaseModel):
    password: str = Field(default="", max_length=128)
    seat_index: int = Field(ge=0, le=MAX_PLAYERS - 1)
    kind: Literal["bot", "empty"]
    # Retired ids are still accepted from old clients and mapped onto the current policy.
    difficulty: Literal["easy", "medium", "hard", "expert", "ledger", "oracle", "boris", "atlas"] = "expert"
    preferred_role: str | None = None
    owner_token: str = Field(default="", max_length=128)


class StartRoomRequest(BaseModel):
    password: str = Field(default="", max_length=128)
    owner_token: str = Field(default="", max_length=128)
    seed: int | None = Field(default=None, ge=0, le=2**32 - 1)


class DeleteRoomRequest(BaseModel):
    password: str = Field(default="", max_length=128)


class CommandRequest(BaseModel):
    password: str = Field(default="", max_length=128)
    type: str = Field(min_length=1, max_length=64)
    actor_id: str = Field(min_length=1, max_length=64)
    payload: dict[str, Any] = Field(default_factory=dict)
    command_id: str | None = Field(default=None, max_length=128)
    expected_revision: int | None = Field(default=None, ge=0)


@lru_cache(maxsize=1)
def get_room_service() -> CityRoomService:
    store = os.getenv("ROOM_STORE", "auto").lower()
    if store not in {"auto", "memory", "upstash"}:
        raise RuntimeError("ROOM_STORE must be auto, memory or upstash")
    has_upstash = bool(
        (os.getenv("UPSTASH_REDIS_REST_URL") and os.getenv("UPSTASH_REDIS_REST_TOKEN"))
        or (os.getenv("KV_REST_API_URL") and os.getenv("KV_REST_API_TOKEN"))
    )
    if store == "auto" and os.getenv("VERCEL") and not has_upstash:
        raise RuntimeError("persistent Upstash credentials are required on Vercel")
    use_upstash = store == "upstash" or (store == "auto" and has_upstash)
    repository = UpstashRoomRepository.from_env() if use_upstash else InMemoryRoomRepository()
    return CityRoomService(repository)


def _market_prices(service: CityRoomService, room: RoomState, viewer_id: str | None) -> dict[str, int] | None:
    """Prices the viewer would actually pay, resolved server-side (see room_view)."""
    if room.game is None or viewer_id is None:
        return None
    try:
        player = room.game.player_by_id(viewer_id)
    except KeyError:
        return None
    return service.engine.market_prices(room.game, player)


def _client(request: Request) -> ClientInfo:
    """The caller's address as the platform reports it, and the browser's label.

    Behind Vercel the socket address is the proxy's, so the forwarded headers come first; the first
    entry of ``X-Forwarded-For`` is the client the proxy saw.
    """
    forwarded = request.headers.get("x-forwarded-for", "").split(",")[0].strip()
    ip = forwarded or request.headers.get("x-real-ip", "").strip() or (request.client.host if request.client else "")
    return ClientInfo(ip=ip[:64], user_agent=request.headers.get("user-agent", "")[:256])


# The administrator's key, from the environment. Shorter than this or unset, the admin endpoints
# answer as if they did not exist: a guessable key is worse than none.
_ADMIN_TOKEN_MIN = 16


def _is_admin(token: str) -> bool:
    expected = os.getenv("ADMIN_TOKEN", "")
    return len(expected) >= _ADMIN_TOKEN_MIN and bool(token) and hmac.compare_digest(token, expected)


def require_admin(admin_token: str = Header(default="", alias="X-Admin-Token")) -> None:
    if not _is_admin(admin_token):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Not Found")


def _admin_room(service: CityRoomService, room: RoomState) -> dict[str, Any]:
    """Everything the administrator sees about a room: seats, who sits in them, and the score so far."""
    game = room.game
    scores = {player.id: service.engine.score(player) for player in game.players} if game else {}
    seats = []
    for seat in room.seats:
        item = seat.to_dict()
        item["client"] = room.seat_clients.get(seat.player_id or "") if seat.kind == "human" else None
        item["score"] = scores.get(seat.player_id or "")
        seats.append(item)
    addresses: dict[str, list[str]] = {}
    for item in seats:
        for ip in (item["client"] or {}).get("ips", []):
            addresses.setdefault(ip, []).append(item["name"] or "")
    return {
        **room.public_summary(),
        "created_at": room.created_at,
        "max_rounds": room.max_rounds,
        "round": game.round_number if game else None,
        "tutorial": room.tutorial,
        "seats": seats,
        # Addresses two or more human seats share — one person at several seats, or one household.
        "shared_ips": {ip: names for ip, names in addresses.items() if len(names) > 1},
    }


@router.get("/admin/rooms", dependencies=[Depends(require_admin)])
def admin_rooms(
    limit: int = Query(default=100, ge=1, le=100),
    service: CityRoomService = Depends(get_room_service),
) -> list[dict[str, Any]]:
    return [_admin_room(service, room) for room in service.list_rooms(limit)]


@router.get("/admin/rooms/{room_id}", dependencies=[Depends(require_admin)])
def admin_room(room_id: str, service: CityRoomService = Depends(get_room_service)) -> dict[str, Any]:
    return _admin_room(service, service.get_room(room_id))


@router.get("/meta")
def meta() -> dict[str, Any]:
    return load_catalog().public_meta()


@router.get("/rooms")
def list_rooms(
    limit: int = Query(default=50, ge=1, le=100),
    service: CityRoomService = Depends(get_room_service),
) -> list[dict[str, Any]]:
    # Tutorial tables are private: nobody can join one, so they never reach the list.
    return [room.public_summary() for room in service.list_rooms(limit) if not room.tutorial]


@router.post("/rooms", status_code=status.HTTP_201_CREATED)
def create_room(
    request: CreateRoomRequest,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    data = request.model_dump(exclude={"open"})
    room = service.create_room(**data, is_open=request.open)
    return room_view(room)


@router.post("/tutorial", status_code=status.HTTP_201_CREATED)
def create_tutorial(
    request: TutorialRequest,
    http: Request,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    """A private tutorial table, already started, with the player on seat 1 to move first."""
    room, password = service.create_tutorial(player_name=request.player_name, lang=request.lang, client=_client(http))
    viewer_id = room.seats[0].player_id
    legal = service.engine.legal_actions(room.game, viewer_id) if room.game is not None else []
    return {
        "password": password,
        "player_id": viewer_id,
        "room": room_view(room, viewer_id, legal, _market_prices(service, room, viewer_id)),
    }


@router.get("/rooms/{room_id}")
def get_room(
    room_id: str,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    room = service.get_room(room_id)
    return {**room.public_summary(), "seats": [seat.to_dict() for seat in room.seats]}


@router.delete("/rooms/{room_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_room(
    room_id: str,
    request: DeleteRoomRequest,
    service: CityRoomService = Depends(get_room_service),
) -> Response:
    service.delete_room(room_id, password=request.password)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.post("/rooms/{room_id}/join")
def join_room(
    room_id: str,
    request: JoinRoomRequest,
    http: Request,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    room = service.join(room_id, **request.model_dump(), client=_client(http))
    viewer_id = room.seats[request.seat_index].player_id
    return room_view(room, viewer_id)


@router.post("/rooms/{room_id}/seats")
def configure_seat(
    room_id: str,
    request: SeatRequest,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    if request.kind == "empty":
        room = service.clear_seat(
            room_id,
            password=request.password,
            seat_index=request.seat_index,
            owner_token=request.owner_token,
        )
    else:
        room = service.set_bot(
            room_id,
            password=request.password,
            seat_index=request.seat_index,
            difficulty=request.difficulty,
            preferred_role=request.preferred_role,
            owner_token=request.owner_token,
        )
    return room_view(room)


@router.post("/rooms/{room_id}/start")
def start_room(
    room_id: str,
    request: StartRoomRequest,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    return room_view(service.start(room_id, **request.model_dump()))


@router.get("/rooms/{room_id}/state")
def get_room_state(
    room_id: str,
    viewer_id: str | None = Query(default=None),
    after_revision: int | None = Query(default=None, ge=0),
    room_password: str = Header(default="", alias="X-Room-Password"),
    admin_token: str = Header(default="", alias="X-Admin-Token"),
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    if after_revision is not None:
        current_revision = service.get_revision(room_id)
        if current_revision == after_revision:
            return {"changed": False, "revision": current_revision}
    room = service.get_room(room_id)
    admin = _is_admin(admin_token)
    if not admin:
        service.authorize_viewer(room, room_password, viewer_id)
    # The administrator watches through any seat but never plays it: no legal actions, and commands
    # still need the room password and a human seat.
    legal_actions = (
        service.engine.legal_actions(room.game, viewer_id)
        if room.game is not None and viewer_id is not None and not admin
        else []
    )
    return {"changed": True, **room_view(room, viewer_id, legal_actions, _market_prices(service, room, viewer_id))}


@router.get("/rooms/{room_id}/journal")
def get_room_journal(
    room_id: str,
    viewer_id: str | None = Query(default=None),
    room_password: str = Header(default="", alias="X-Room-Password"),
    admin_token: str = Header(default="", alias="X-Admin-Token"),
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    """Replayable record of a finished match: seed, command journal and the final snapshot.

    Rooms expire, so a match that is not exported is gone; this is what makes a game analysable
    after the fact instead of only readable in the chronicle while the room still exists.
    """
    room = service.get_room(room_id)
    if not _is_admin(admin_token):
        service.authorize_viewer(room, room_password, viewer_id)
    try:
        return room_journal(room)
    except ValueError as exc:
        raise RoomValidationError(str(exc)) from exc


@router.post("/rooms/{room_id}/commands")
def apply_command(
    room_id: str,
    request: CommandRequest,
    http: Request,
    service: CityRoomService = Depends(get_room_service),
) -> dict[str, Any]:
    data = request.model_dump(exclude={"password"})
    room = service.apply_command(
        room_id, password=request.password, command=Command.from_dict(data), client=_client(http)
    )
    legal_actions = service.engine.legal_actions(room.game, request.actor_id) if room.game is not None else []
    return room_view(room, request.actor_id, legal_actions, _market_prices(service, room, request.actor_id))
